---
location: test
port: 4567
#midi_server_host: piano.local
midi_server_host: 127.0.0.1
midi_server_port: 55554
fps: 30
#strip: dummy
strip: terminal
nr_of_leds: 80
bind: 0.0.0.0:4567
topic: seehaus/command
